name: Build C# Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # or '7.0.x', etc., based on your project

      - name: Restore dependencies
        run: dotnet restore

      - name: Build plugin
        run: dotnet publish AnythingButton/AnythingButton.csproj -c Release -f net7.0-windows

      - name: Run tests (optional)
        run: dotnet test --no-build --verbosity normal

      - name: Publish application
        run: dotnet publish -c Release -o out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-app
          path: out/
